//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int MaHD { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaDon { get; set; }
        public Nullable<decimal> GiaDV { get; set; }
        public Nullable<decimal> GiaPhuThu { get; set; }
        public Nullable<decimal> GiaHoaHong { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string TinhTrangHD { get; set; }
    
        public virtual DonDat DonDat { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
