//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachSan()
        {
            this.Phongs = new HashSet<Phong>();
        }
    
        public int MaKS { get; set; }
        public Nullable<int> MaDT { get; set; }
        public string TenKS { get; set; }
        public Nullable<int> SoSao { get; set; }
        public string DiaChi { get; set; }
        public string Anh { get; set; }
        public string TienIch { get; set; }
        public string ChinhSach { get; set; }
        public string DanhGia { get; set; }
    
        public virtual DoiTac DoiTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
