//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeMayBay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VeMayBay()
        {
            this.ChiTietVeMayBays = new HashSet<ChiTietVeMayBay>();
        }
    
        public int MaVeMB { get; set; }
        public Nullable<int> MaDT { get; set; }
        public string TenVe { get; set; }
        public string Anh { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> MaTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietVeMayBay> ChiTietVeMayBays { get; set; }
        public virtual DoiTac DoiTac { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
    }
}
