//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int MaBinhLuan { get; set; }
        public Nullable<int> MaNguoiDung { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual BinhLuanPhong BinhLuanPhong { get; set; }
        public virtual BinhLuanTourDuLich BinhLuanTourDuLich { get; set; }
        public virtual BinhLuanThueXe BinhLuanThueXe { get; set; }
        public virtual BinhLuanVeMayBay BinhLuanVeMayBay { get; set; }
        public virtual BinhLuanVeXeKhach BinhLuanVeXeKhach { get; set; }
    }
}
