//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int MaCT { get; set; }
        public Nullable<int> MaDon { get; set; }
        public Nullable<int> MaDV { get; set; }
        public string ChiTiet { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual DichVu DichVu { get; set; }
    }
}
