//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoiTac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DoiTac()
        {
            this.DichVus = new HashSet<DichVu>();
            this.TinTucs = new HashSet<TinTuc>();
        }
    
        public int MaDT { get; set; }
        public Nullable<int> MaLoaiDV { get; set; }
        public Nullable<int> MaLoaiDT { get; set; }
        public string TenDT { get; set; }
        public string AnhLogo { get; set; }
        public string ThongTinChiTiet { get; set; }
        public string ThongTinLienHe { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaTK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu> DichVus { get; set; }
        public virtual LoaiDoiTac LoaiDoiTac { get; set; }
        public virtual LoaiDichVu LoaiDichVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinTuc> TinTucs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
