//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThueXe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThueXe()
        {
            this.ChiTietChoThueXes = new HashSet<ChiTietChoThueXe>();
            this.BinhLuanThueXes = new HashSet<BinhLuanThueXe>();
        }
    
        public int MaThueXe { get; set; }
        public Nullable<int> MaDT { get; set; }
        public string TenXe { get; set; }
        public string Anh { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> MaTT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietChoThueXe> ChiTietChoThueXes { get; set; }
        public virtual DoiTac DoiTac { get; set; }
        public virtual TinhTrang TinhTrang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuanThueXe> BinhLuanThueXes { get; set; }
    }
}
