//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinTuc
    {
        public int MaTinTuc { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TacGia { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public Nullable<int> MaDoiTac { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
    
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual DoiTac DoiTac { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
