//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class voucher
    {
        public int MaVoucher { get; set; }
        public string MaCode { get; set; }
        public decimal discount { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
    }
}
