//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDTProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuThich
    {
        public int MaYeuThich { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaDV { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
